version: '3.7'
services:
  keycloak:
    image: "mygammon/keycloak:v1"
    ports:
      - "8081:8080"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
  postgres:
    image: "postgres:11.0"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - "dbdata:/var/lib/postgresql/data/dbdata"
volumes:
  dbdata: