version: '3.7'

services:
  keycloak:
    build:
      dockerfile: dockerfile
      context: ../keycloak/backgammon-vertx
    volumes:
      - "keycloak:/opt/jboss/keycloak/standalone"
    ports:
      - "8080:8080"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
  postgres:
    image: "postgres:11.0"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - "postgres:/var/lib/postgresql/data/dbdata"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
volumes:
  keycloak:
  postgres:
  elasticsearch:
