FROM ceylon/ceylon:1.3.3

COPY dist/client /app/client
COPY dist/modules /app/modules
COPY dist/static /app/static
COPY resource /app/resource
EXPOSE 8081
CMD ceylon run --overrides=resource/overrides.xml --flat-classpath backgammon.server 